### ISSUE TITLE
Should check postId in FacebookContext

### ISSUE THREAD

**Issue by kpman** [bottenderjs/bottender-facebook#18]
https://github.com/bottenderjs/bottender-fb/blob/aa041a1edc688e7607923239bd9ccc86b6665f38/src/FacebookContext.js#L8

https://github.com/bottenderjs/bottender-fb/blob/aa041a1edc688e7607923239bd9ccc86b6665f38/src/FacebookContext.js#L18

**Comment by wtflink** [comment]
outdated
