### ISSUE TITLE
should handle feed like events

### ISSUE THREAD

**Issue by tw0517tw** [bottenderjs/bottender-facebook#29]
```
   {
     "field": "feed",
     "value": {
       "item": "like",
       "verb": "add"
     }
   }
```

**Comment by kpman** [comment]
https://developers.facebook.com/docs/graph-api/webhooks/reference/page/
search `feed`

**Comment by wtflink** [comment]
We can handle those event with:
https://github.com/bottenderjs/bottender-facebook/blob/master/src/FacebookEvent.js#L148-L158
https://github.com/bottenderjs/bottender-facebook/blob/3ec8538d119b41dc5daabf76353967a65b7b63a3/src/FacebookEvent.js#L167-L182
