### ISSUE TITLE
context.sendLike

### ISSUE THREAD

**Issue by Calvin-Lin** [bottenderjs/bottender-facebook#34]
It would be better if I can send like to the comment through something like `context.sendLike`

**Comment by Calvin-Lin** [comment]
https://developers.facebook.com/docs/graph-api/reference/v2.12/object/likes

**Comment by chentsulin** [comment]
```
like
unlike
```

Or

```
sendLike
retrieveLike
````

@bottenderjs/members

**Comment by tw0517tw** [comment]
like / unlike +1

**Comment by kpman** [comment]
`sendLike` is confused. Is it sending object like or sending like emoji(thumb) in message?

But if we want to keep the consistency, the naming may follow as:
- [Object Private Reply](https://developers.facebook.com/docs/graph-api/reference/v2.12/object/private_replies) => [context.sendPrivateReply](https://github.com/bottenderjs/bottender-facebook/blob/master/src/FacebookContext.js#L7)
- [Object Comments](https://developers.facebook.com/docs/graph-api/reference/v2.12/object/comments) => [context.sendComment](https://github.com/bottenderjs/bottender-facebook/blob/master/src/FacebookContext.js#L20)
- [Object Likes](https://developers.facebook.com/docs/graph-api/reference/object/likes/) => `context.sendLike`

**Comment by chentsulin** [comment]
private_replies -> write
comments -> read, write, delete
likes -> read, write, delete
reactions -> read
sharedposts -> read

**Comment by chentsulin** [comment]
We already have `context.sendLike` now
