### ISSUE TITLE
some action should be able to perform with postId

### ISSUE THREAD

**Issue by wtflink** [bottenderjs/bottender-facebook#53]
https://github.com/bottenderjs/bottender-facebook/blob/3ec8538d119b41dc5daabf76353967a65b7b63a3/src/FacebookContext.js#L68-L75

https://github.com/bottenderjs/bottender-facebook/blob/3ec8538d119b41dc5daabf76353967a65b7b63a3/src/FacebookContext.js#L44-L50

**Comment by chentsulin** [comment]
fix in https://github.com/Yoctol/bottender/pull/569
